version: "2"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - dupword
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - gosmopolitan
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - paralleltest
    - prealloc
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
    lll:
      line-length: 160
    recvcheck:
      disable-builtin: true
      exclusions:
        - '*.String'
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
