linters:
  enable-all: true
  disable:
    - cyclop
    - containedctx
    - contextcheck
    - depguard
    - dupl
    - dupword
    - exhaustruct
    - exportloopref
    - gocognit
    - gocyclo
    - gocritic
    - gochecknoinits
    - funlen
    - ireturn
    - err113
    - mnd
    - nestif
    - testpackage
    - paralleltest
    - prealloc
    - maintidx
    - gochecknoglobals
    - gosmopolitan
    - varnamelen
    - tagliatelle
    - lll
    - wrapcheck

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck

linters-settings:
  lll:
    line-length: 160
  errcheck:
    exclude-functions:
      # Used in HTTP handlers, any error is handled by the server itself.
      - (net/http.ResponseWriter).Write
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        severity: warning
        disabled: true
  recvcheck:
    # Disables the built-in method exclusions:
    # - `MarshalText`
    # - `MarshalJSON`
    # - `MarshalYAML`
    # - `MarshalXML`
    # - `MarshalBinary`
    # - `GobEncode`
    # Default: false
    disable-builtin: true
    # User-defined method exclusions.
    # The format is `struct_name.method_name` (ex: `Foo.MethodName`).
    # A wildcard `*` can use as a struct name (ex: `*.MethodName`).
    # Default: []
    exclusions:
      - "*.String"
