export const testIds = {
  appConfig: {
    appUrl: "data-testid ac-url",
    skipTlsCheck: "data-testid ac-skip-tls-check",
    saToken: "data-testid ac-sa-token",
    container: "data-testid ac-container",
    theme: "data-testid ac-theme",
    layout: "data-testid ac-layout",
    orientation: "data-testid ac-orientation",
    dashboardMode: "data-testid ac-dashboard-mode",
    tz: "data-testid ac-timezone",
    tf: "data-testid ac-timeformat",
    logo: "data-testid ac-logo",
    headerTemplate: "data-testid ac-header-template",
    footerTemplate: "data-testid ac-footer-template",
    maxBrowserWorkers: "data-testid ac-max-browser-workers",
    maxRenderWorkers: "data-testid ac-max-render-workers",
    remoteChromeUrl: "data-testid ac-remote-chrome-url",
    submit: "data-testid ac-submit-form",
  },
  Status: {
    container: "data-testid pg-one-container",
    health: "data-testid pg-one-health",
    config: "data-testid pg-one-config",
  },
  Panel: {
    container: "data-testid Panel header Repeated Panel",
    reportLink: "data-testid Dashboard link container",
  },
};
